name: Run Tests

on:
  push:
    branches:
      - main   # Or your main branch name (master, etc.)

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18   # Your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test   # Remove or comment out if you have no tests
